baseURL = "/"
title = "Threat Models"
languageCode = "en-us"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]

[params]
  showToc = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
